### ISSUE TITLE
Support local only fonts 

### ISSUE THREAD

**Issue by eladmoshe** [capriza/capp-cache#24]
For example:
The following manifest

```json
 {
      "type": "fontface",
      "fontAttributes": {
        "font-family": "Roboto",
        "font-style": "italic",
        "font-weight": "300"
      },
      "localFontFamily": ["Roboto", "Roboto-LightItalic"]
    },```
should create the following rule

```css
@font-face {
  font-family: 'Roboto';
  font-style: italic;
  font-weight: 100;
  src: local("Roboto Thin Italic"), local("Roboto-ThinItalic");
}
```

Requested by @nadavoran

**Comment by eladmoshe** [comment]
@nadavoran - check out the manifest. Does that work for you?

**Comment by eladmoshe** [comment]
Note that I eliminated the format from the the src, I don't think it is valid for local fonts.

**Comment by nadavoran** [comment]
yes
Also, how can I trigger an onload function to validate fonts loaded before displaying the mobile?

**Comment by eladmoshe** [comment]
You should be able to use the same `onload` attribute. Note that his goes to the regular `attributes` rather than to `fontAttributes`

**Comment by eladmoshe** [comment]
We agreed to use regular CSS for this use case
